language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfest-sydney-2017
  token:
    secure: "P5kbKeVcDf7fBJR24TxkkXq9/8sA5mGI62HiRYtaWrGgaU7j5UP5r8lfHfVLhP/aMpDkZsWgE2lsulGup7NaRxmz3idsOM1wDMZFyEChshop+c5TwSD9N+FvQfPJe+6eMO2fSJkc6kBQW8+jf/2bI200zgo/BJs+Vwda6skkY4+ejDBDtg44GnEoyrIFUajd4SbHQfGv/lf/V5rfEfzsRol0hGmAM09OuKatTucwyiuYPqgv4TGjsfRrPLZDwox538VTJ2G8nP5/YuLuj0qKBE9YFPeYnntoPWjIEwyV4U4LOFPOf3O183DIOWDBLuCrn1ZR6CjDH4rnLlJcjxvtNd1Ad3H10FuW9f1bgW+7esxvacIj2/nb8YiQ/xPU39efg4PgzPFaxjhz8Z3uWZyv2EjY7/+RBe8LnE4U6pTsZfSIAJnBsO0d6+13iysVUHjg2/aearX9mbhJ5H7+sI6m5u3bYCUpkqw6IbMXr80UrHDJy/u6bf9Im+/PeAwQ3kN4XX9whKCttMrHnWtBirK4PFISld2LoR18LbwjdWaUXzy62RoFFnPAbI9JhQtWt91mVwFzjIfeeWzkcTutYlbvqL8jp0Uo07FJprYE5ER7JMvqWUgh90IhRjjWb6g/d1kHctt4YFGBMr4Ec+mWvweE3Mj8gtq/UJ6COLBgAKO/Zvo="
